In [1]:
import os
!mkdir -p ~/.kaggle && echo KGAT_6d40782e01b421cb477505679856f6d7 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

!kaggle datasets download -d mad2112/blinkit-retail-analytics-and-dashboard
!unzip -o -q blinkit-retail-analytics-and-dashboard.zip -d blinkit_data

# list the downloaded files
print("Files downloaded successfully:")
print(os.listdir('blinkit_data'))

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/mad2112/blinkit-retail-analytics-and-dashboard
License(s): CC0-1.0
Downloading blinkit-retail-analytics-and-dashboard.zip to /content
100% 12.1M/12.1M [00:01<00:00, 12.7MB/s]

Files downloaded successfully:
['blinkit_orders.csv', 'blinkit_products.csv', 'blinkit_order_items.csv', 'Blinkit_Dashboard_Report.pbix', 'blinkit_delivery_performance.csv', 'blinkit_marketing_performance.csv', 'blinkit_customers.csv', 'Blinkit_Dashboard_Report.pdf', 'blinkit_inventory.csv', 'blinkit_customer_feedback.csv']

In [4]:
import pandas as pd

orders = pd.read_csv('blinkit_data/blinkit_orders.csv')
items = pd.read_csv('blinkit_data/blinkit_order_items.csv')
delivery = pd.read_csv('blinkit_data/blinkit_delivery_performance.csv')
feedback = pd.read_csv('blinkit_data/blinkit_customer_feedback.csv')

print("ORDERS TABLE")
display(orders.head())

print("ORDER ITEMS TABLE")
display(items.head())

print("DELIVERY PERFORMANCE TABLE")
display(delivery.head())

print("CUSTOMER FEEDBACK TABLE")
display(feedback.head())

ORDERS TABLE

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

ORDER ITEMS TABLE

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

DELIVERY PERFORMANCE TABLE

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

CUSTOMER FEEDBACK TABLE

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20

In [17]:
# check for null/missing values in each of these transactions table
# and the total number of data in each of the tables
print("ORDER TABLE")
print(f"count: {len(orders):,}")
print(orders.isnull().sum())

print("ORDER ITEM TABLE")
print(f"count: {len(items):,}")
print(items.isnull().sum())

print("DELIVERY PERFORMANCE TABLE")
print(f"count: {len(delivery):,}")
print(delivery.isnull().sum())

print("CUSTOMER FEEDBACK TABLE")
print(f"count: {len(feedback):,}")
print(feedback.isnull().sum())

ORDER TABLE
count: 5,000
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64
ORDER ITEM TABLE
count: 5,000
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64
DELIVERY PERFORMANCE TABLE
count: 5,000
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64
CUSTOMER FEEDBACK TABLE
count: 5,000
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [19]:
# check the delay reasons
print(delivery['reasons_if_delayed'].value_counts(dropna=False))

reasons_if_delayed
Traffic    3098
NaN        1902
Name: count, dtype: int64

In [22]:
print(delivery['delivery_time_minutes'].describe())
print(delivery['distance_km'].describe())

count    5000.000000
mean        4.443000
std         8.063929
min        -5.000000
25%        -1.000000
50%         2.000000
75%         8.000000
max        30.000000
Name: delivery_time_minutes, dtype: float64
count    5000.000000
mean        2.718048
std         1.290306
min         0.500000
25%         1.590000
50%         2.690000
75%         3.850000
max         5.000000
Name: distance_km, dtype: float64

In [23]:
# verify timestamp calculation against delivery_time_minutes
display(delivery[['promised_time', 'actual_time', 'delivery_time_minutes', 'reasons_if_delayed']].head(5))

,promised_time,actual_time,delivery_time_minutes,reasons_if_delayed
0,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,NaN
1,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,Traffic
2,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,Traffic
3,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,NaN
4,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,Traffic

In [26]:
# master operational CSV
import pandas as pd
from google.colab import files

# rename delivery_time_minutes to SLA_delay_minutes
delivery_clean = delivery[['order_id', 'delivery_partner_id', 'delivery_time_minutes', 'distance_km', 'reasons_if_delayed']].copy()
delivery_clean.rename(columns={'delivery_time_minutes': 'sla_delay_minutes'}, inplace=True)

# left join Delivery, Customer Feedback, and Order Items
df_master = orders.merge(delivery_clean, on='order_id', how='left')
df_master = df_master.merge(feedback[['order_id', 'rating', 'feedback_category', 'sentiment']], on='order_id', how='left')
df_master = df_master.merge(items[['order_id', 'product_id', 'quantity', 'unit_price']], on='order_id', how='left')

df_master.to_csv('blinkit_operational_master.csv', index=False)
print("Consolidation complete! Total rows:", len(df_master))
files.download('blinkit_operational_master.csv')

Consolidation complete! Total rows: 5000